version: '3.8'
services:
  dokemon:
    image: productiveops/dokemon:latest
    container_name: dokemon
    restart: on-failure
    ports:
      - 9091:9090
    volumes:
      - /containers/dokemon/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
networks: {}
