version: '3.3'
services:
  dokemon:
    image: productiveops/dokemon:latest
    container_name: dokemon
    restart: unless-stopped
    ports:
      - 9091:9090
    volumes:
      - /containers/dokemon/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
networks: {}