---

services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: always
    ports:
      - 5001:5001
    environment:
      - DOCKGE_STACKS_DIR=/home/$USER/saffron/stacks
      - USER=$USER # to pass down to use in other stacks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /containers/dockge/data:/app/data
      - /home/$USER/saffron/stacks:/home/$USER/saffron/stacks
      - /etc/timezone:/etc/timezone:ro