version: '3.8'
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: on-failure
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=info
    networks:
      - servarr_bridge
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: on-failure
    ports:
      - 9696:9696
    env_file:
      - .env.public
    volumes:
      - /containers/prowlarr:/config
    networks:
      - servarr_bridge
  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    restart: on-failure
    privileged: true
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    env_file:
      - .env.public
    volumes:
      - /containers/qbittorrent/:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra # optional
    networks:
      - servarr_bridge
networks:
  servarr_bridge:
    external: true

# .env must define: VPN_ENABLED, VPN_USERNAME, VPN_PASSWORD, & DATA_DIR (other DIR's can be deleted)
# also requires a .ovpn file in the /containers/qbittorrent/openvpn/ folder for VPN use
