version: "3.8"
services:
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: always
    ports:
      - 8191:8191
    networks:
      - servarr_bridge
    extends:
      file: ../common.yaml
      service: base-settings
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    ports:
      - 9696:9696
    env_file:
      - .env.public
    volumes:
      - /containers/prowlarr:/config
    networks:
      - servarr_bridge
  qbittorrentvpn:
    image: dyonr/qbittorrentvpn
    container_name: qbittorrentvpn
    restart: always
    privileged: true
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    extends:
      file: ../common.yaml
      service: media-access
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
    env_file:
      - .env.public
    volumes:
      - /containers/qbittorrent/config:/config
    networks:
      - default
      - servarr_bridge
networks:
  default:
    driver: bridge
  servarr_bridge:
    external: true
