version: "3.8"
services:
  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true
    volumes:
      - /containers/qbittorrent/:/config
      - ${DATA_DIR}:/data/
      - ${DATA_DIR_EXTRA}:/extra/ # optional
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    restart: unless-stopped
    env_file:
      - .env.public
    networks:
      - servarr_bridge
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    env_file:
      - .env.public
    volumes:
      - /containers/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - servarr_bridge
  flaresolverr:
    container_name: flaresolverr
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    image: ghcr.io/flaresolverr/flaresolverr:latest
    networks:
      - servarr_bridge
networks:
  servarr_bridge:
    external: true

# .env must define: VPN_ENABLED, VPN_USERNAME, VPN_PASSWORD, & DATA_DIR (other DIR's can be deleted)
# also requires a .ovpn file in the /containers/qbittorrent/openvpn/ folder for VPN use
