version: "3.8"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:5.2.3
    pull_policy: missing
    container_name: qbittorrent
    restart: unless-stopped
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/qbittorrent:/config/
    environment:
      TORRENTING_PORT: $VPN_INPUT_PORT
    #  DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod:sha-71ff0ec
    network_mode: service:qbittorrentvpn
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test:
        - CMD
        - wget
        - -qO-
        - --timeout=2
        - http://localhost:8080
      start_period: 30s
      interval: 10s
      timeout: 3s
      retries: 3
  portcheck:
    container_name: portcheck
    depends_on:
      qbittorrent:
        condition: service_healthy
    environment:
      QBITTORRENT_PORT: $VPN_INPUT_PORT
      QBITTORRENT_USERNAME: $USER
      QBITTORRENT_PASSWORD: $PASSWORD
    # portcheck has no semver tags; latest is the only tag available
    image: eiqnepm/portcheck:latest
    pull_policy: always
    network_mode: service:qbittorrentvpn
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
  qbittorrentvpn:
    image: qmcgaw/gluetun:v3.41.3
    pull_policy: missing
    container_name: qbittorrentvpn
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # Web UI
      - 8000:8000 # Control Server
    volumes:
      - /containers/gluetun:/gluetun
    environment:
      VPN_TYPE: wireguard
      UPDATER_PERIOD: 24h
      FIREWALL_VPN_INPUT_PORTS: $PORTS
      VPN_PORT_FORWARDING_LISTENING_PORT: $TRACKER_PORT
      HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH: /gluetun/config.toml
      VPN_SERVICE_PROVIDER: $PROVIDER
      WIREGUARD_PRIVATE_KEY: $PRIVATE_KEY
      WIREGUARD_PRESHARED_KEY: $PRESHARED_KEY
      WIREGUARD_ADDRESSES: $ADDRESSES
      SERVER_REGIONS: $REGIONS
    extends:
      file: ../common.yaml
      service: media-access
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - servarr_bridge
networks:
  servarr_bridge:
    external: true
