services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: always
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/qbittorrent:/config/
    environment:
      TORRENTING_PORT: 58217
    network_mode: service:qbittorrentvpn
  qbittorrentvpn:
    image: qmcgaw/gluetun
    container_name: qbittorrentvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080 # Web UI
      - 58217:58217 # Torrenting
      - 58217:58217/udp # Torrenting
    volumes:
      - /containers/gluetun:/gluetun
    environment:
      FIREWALL_VPN_INPUT_PORTS: 58217
      VPN_SERVICE_PROVIDER: $PROVIDER
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: $PRIVATE_KEY
      WIREGUARD_PRESHARED_KEY: $PRESHARED_KEY
      WIREGUARD_ADDRESSES: $ADDRESSES
    extends:
      file: ../common.yaml
      service: media-access
    networks:
      - servarr_bridge
networks:
  servarr_bridge:
    external: true
