version: "3.8"
services:
  backrest:
    image: ghcr.io/garethgeorge/backrest:v1.14.1
    pull_policy: missing
    container_name: backrest
    extends:
      file: ../common.yaml
      service: base-settings
    volumes:
      - /containers/backrest/data:/data
      - /containers/backrest/config:/config
      - /containers/backrest/cache:/cache
      - /containers/backrest/tmp:/tmp
      - /containers/:/userdata/containers
      - ${HOME}/saffron:/userdata/saffron
      - /data/tv:/userdata/tv
      - /data/movies:/userdata/movies
      - /data/music:/userdata/music
      - /data/backrest:/restore
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=America/Los_Angeles
    ports:
      - 9898:9898
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
networks: {}
