version: "3.8"
services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    restart: always
    ports:
      - 85:80
    volumes:
      - /containers/octoprint:/octoprint
    privileged: true
    extends:
      file: ../common.yaml
      service: base-settings
networks: {}
