version: "3.8"
services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    restart: unless-stopped
    ports:
      - 87:80
    privileged: true
    volumes:
      - /containers/octoprint:/octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
networks: {}
