version: '3.8'
services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    restart: unless-stopped
    privileged: true
    ports:
      - 87:80
    environment:
      - ENABLE_MJPG_STREAMER=true
    volumes:
      - /containers/octoprint:/octoprint
networks: {}