version: "2"
services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - 9001:9000
    restart: always
    volumes:
      - /containers/thelounge:/var/opt/thelounge # bind lounge config from the host's file system
networks: {}
