version: '3.8'
services:
  thelounge:
    image: thelounge/thelounge:latest
    container_name: thelounge
    restart: always
    ports:
      - 9001:9000
    volumes:
      - /containers/thelounge:/var/opt/thelounge
networks: {}
# to add a theme docker exec --user node -it thelounge thelounge install theme
# to add a user: docker exec --user node -it thelounge thelounge add username
