version: "2"
services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - 9001:9000
    restart: always
    volumes:
      - /containers/thelounge:/var/opt/thelounge # bind lounge config from the host's file system
networks: {}
# to add a theme docker exec --user node -it thelounge thelounge install theme
# to add a user: docker exec --user node -it thelounge thelounge add username