version: '3.8'
services:
  netboot:
    image: linuxserver/netbootxyz:latest
    container_name: netboot
    restart: on-failure
    ports:
      - 3300:3000
      - 369:69/udp
      - 38080:80
    extends:
      file: ../common.yaml
      service: base-settings
    volumes:
      - /containers/netbootxyz/config:/config
      - /containers/netbootxyz/assets:/assets
networks: {}
