version: "3.8"
services:
  watchyourlan:
    image: aceberg/watchyourlan:2.1.4
    pull_policy: missing
    container_name: watchyourlan
    restart: unless-stopped
    network_mode: host
    ports:
      - 8840:8840
    environment:
      IFACES: ${IFACES:-eth0}
      TZ: America/Los_Angeles
    volumes:
      - /containers/watchyourlan/data:/data/WatchYourLAN
    deploy:
      resources:
        limits:
          memory: 256M
networks: {}
