version: '3'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: on-failure
    network_mode: host
    privileged: true
    ports:
      - 8123:8123
    volumes:
      - /containers/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
networks: {}