version: "3.8"
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: always
    privileged: true
    ports:
      - 8123:8123
    volumes:
      - /containers/homeassistant/config:/config
      - /run/dbus:/run/dbus:ro
    extends:
      file: ../common.yaml
      service: base-settings
    network_mode: host
    