version: '3.8'
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: on-failure[:3]
    ports:
      - 8081:80
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
    volumes:
      - /containers/speedtest-tracker/config:/config
      - /etc/timezone:/etc/timezone:ro
networks: {}