version: "3.8"
services:
  speedtest-tracker:
    image: linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: on-failure
    ports:
      - 8081:80
    environment:
      - DB_CONNECTION=sqlite
    env_file:
      - ../common.env.public
    volumes:
      - /containers/speedtest-tracker/config:/config
      - /etc/timezone:/etc/timezone:ro
networks: {}
