version: "3.8"
services:
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: on-failure
    ports:
      - 6767:6767
    env_file:
      - ../common.env.public
    volumes:
      - /containers/bazarr:/config
      - ${DATA_DIR}:/data
      - ${EXTRA_DIR}:/extra
      - ${BULK_DIR}:/bulk
      - /etc/timezone:/etc/timezone:ro
    networks:
      - bridge
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: on-failure
    ports:
      - 8686:8686
    env_file:
      - ../common.env.public
    volumes:
      - /containers/lidarr:/config
      - ${DATA_DIR}:/data
      - ${EXTRA_DIR}:/extra
      - ${BULK_DIR}:/bulk
      - /etc/timezone:/etc/timezone:ro
    networks:
      - bridge
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: on-failure
    ports:
      - 7878:7878
    env_file:
      - ../common.env.public
    volumes:
      - /containers/radarr:/config
      - ${DATA_DIR}:/data
      - ${EXTRA_DIR}:/extra
      - ${BULK_DIR}:/bulk
      - /etc/timezone:/etc/timezone:ro
    networks:
      - bridge
  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    restart: on-failure
    ports:
      - 8787:8787
    env_file:
      - ../common.env.public
    volumes:
      - /containers/readarr/config:/config
      - /containers/readarr/books:/books
      - ${DATA_DIR}:/data
      - ${EXTRA_DIR}:/extra
      - /etc/timezone:/etc/timezone:ro
    networks:
      - bridge
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: on-failure
    ports:
      - 8989:8989
    env_file:
      - ../common.env.public
    volumes:
      - /containers/sonarr:/config
      - ${DATA_DIR}:/data
      - ${EXTRA_DIR}:/extra
      - ${BULK_DIR}:/bulk
      - /etc/timezone:/etc/timezone:ro
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
