version: "3.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - .env.public
    volumes:
      - /containers/sonarr:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra # optional
      - ${BULK_DIR}:/bulk # optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      bridge: null
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - .env.public
    volumes:
      - /containers/radarr:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra # optional
      - ${BULK_DIR}:/bulk # optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      bridge: null
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    env_file:
      - .env.public
    volumes:
      - /containers/lidarr:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra # optional
      - ${BULK_DIR}:/bulk # optional
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      bridge: null
  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    env_file:
      - .env.public
    volumes:
      - /containers/readarr/config:/config
      - /containers/readarr/books:/books
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra # optional
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      bridge: null
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    env_file:
      - .env.public
    volumes:
      - /containers/bazarr:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra # optional
      - ${BULK_DIR}:/bulk # optional
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      bridge: null
networks:
  bridge:
    driver: bridge

# .env must define DATA_DIR