version: '3.8'
services:
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: on-failure
    ports:
      - 6767:6767
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/bazarr:/config
    networks:
      - bridge
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: on-failure
    ports:
      - 8686:8686
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/lidarr:/config
    networks:
      - bridge
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: on-failure
    ports:
      - 7878:7878
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/radarr:/config
    networks:
      - bridge
  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    restart: on-failure
    ports:
      - 8787:8787
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/readarr/config:/config
      - /containers/readarr/books:/books
    networks:
      - bridge
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: on-failure
    ports:
      - 8989:8989
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/sonarr:/config
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
