version: '3.1'
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    ports:
      - 6767:6767
    env_file:
      - .env.public
    volumes:
      - /containers/bazarr:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra
      - ${BULK_DIR}:/bulk
      - /etc/timezone:/etc/timezone:ro
    networks:
      bridge: null
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    ports:
      - 8686:8686
    env_file:
      - .env.public
    volumes:
      - /containers/lidarr:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra
      - ${BULK_DIR}:/bulk
      - /etc/timezone:/etc/timezone:ro
    networks:
      bridge: null
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    env_file:
      - .env.public
    volumes:
      - /containers/radarr:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra
      - ${BULK_DIR}:/bulk
      - /etc/timezone:/etc/timezone:ro
    networks:
      bridge: null
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: unless-stopped
    ports:
      - 8787:8787
    env_file:
      - .env.public
    volumes:
      - /containers/readarr/config:/config
      - /containers/readarr/books:/books
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra
      - /etc/timezone:/etc/timezone:ro
    networks:
      bridge: null
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    env_file:
      - .env.public
    volumes:
      - /containers/sonarr:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra
      - ${BULK_DIR}:/bulk
      - /etc/timezone:/etc/timezone:ro
    networks:
      bridge: null
networks:
  bridge:
    driver: bridge