version: "3.8"
services:
  watchtower:
    image: containrrr/watchtower:1.7.1
    pull_policy: missing
    container_name: watchtower
    restart: always
    extends:
      file: ../common.yaml
      service: base-settings
    environment:
      - WATCHTOWER_CLEANUP=true # remove orphaned images
      - WATCHTOWER_POLL_INTERVAL=43200 # run every 12 hours
      - DOCKER_API_VERSION=1.52
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - saffron_default
networks:
  saffron_default:
    external: true
