version: "3.8"
services:
  prowlarr:
    image: linuxserver/prowlarr:2.6.1-develop
    pull_policy: missing
    container_name: prowlarr
    restart: always
    ports:
      - 9696:9696
    extends:
      file: ../common.yaml
      service: base-settings
    volumes:
      - /containers/prowlarr:/config
    networks:
      - servarr_bridge
  flaresolverr:
    image: flaresolverr/flaresolverr:v3.5.0
    pull_policy: missing
    container_name: flaresolverr
    restart: always
    ports:
      - 8191:8191
    networks:
      - servarr_bridge
  byparr:
    container_name: byparr
    image: ghcr.io/thephaseless/byparr:latest
    pull_policy: always
    restart: unless-stopped
    shm_size: 2gb
    ports:
      - 8192:8191
    networks:
      - servarr_bridge
networks:
  servarr_bridge:
    external: true
