version: "3.8"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=13008
    env_file:
      - general.env
    volumes:
      - ${CONFIG_DIR}/jellyfin-config:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra
    ports:
      - 8096:8096
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    networks:
      - servarr_bridge
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    env_file:
      - general.env
    ports:
      - 5057:5055
    volumes:
      - ${CONFIG_DIR}/jellyseerr-config/:/app/config
    restart: unless-stopped
    networks:
      - servarr_bridge
networks:
  servarr_bridge:
    external: true
