version: "3.8"
services:
  plex:
    image: linuxserver/plex:1.43.3
    pull_policy: missing
    container_name: plex
    network_mode: host
    environment:
      VERSION: docker
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri # for intel hardware decode
    extends:
      file: ../common.yaml
      service: media-access
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - /containers/plex:/config
  seerr:
    image: ghcr.io/seerr-team/seerr:v3.0.1
    pull_policy: missing
    container_name: seerr
    extends:
      file: ../common.yaml
      service: base-settings
    volumes:
      - /containers/overseerr/config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      - servarr_bridge
networks:
  servarr_bridge:
    external: true
