version: "3.8"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - VERSION=docker
      - PLEX_CLAIM= #optional
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri # for intel hardware decode
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/plex:/config
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    extends:
      file: ../common.yaml
      service: base-settings
    volumes:
      - /containers/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      - servarr_bridge
networks:
  servarr_bridge:
    external: true
