version: "3.9"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: always
    ports:
      - 8280:8081
    volumes:
      - /data/metube:/downloads
    extends:
      file: ../common.yaml
      service: media-access
    networks:
      - saffron_default
networks:
  saffron_default:
    external: true
