version: "3"
services:
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    ports:
      - 8000:8000 # HTTP
      - 8443:8443 # HTTPS
      - 8124:8123 # DYNMAP
      - 19132:19132/udp # BEDROCK
      - 25500-25600:25500-25600 # MC SERV PORT RANGE
    volumes:
      - /containers/crafty/backups:/crafty/backups
      - /containers/crafty/logs:/crafty/logs
      - /containers/crafty/servers:/crafty/servers
      - /containers/crafty/config:/crafty/app/config
      - /containers/crafty/import:/crafty/import
      - /etc/timezone:/etc/timezone:ro
networks: {}
