version: "3.8"
services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    container_name: crafty
    restart: on-failure
    ports:
      - 8000:8000 # http
      - 8443:8443 # https
      - 8124:8123 # dynmap
      - 19132:19132/udp # bedrock
      - 25500-25600:25500-25600 # mc server port range
    volumes:
      - /containers/crafty/backups:/crafty/backups
      - /containers/crafty/logs:/crafty/logs
      - /containers/crafty/servers:/crafty/servers
      - /containers/crafty/config:/crafty/app/config
      - /containers/crafty/import:/crafty/import
      - /etc/timezone:/etc/timezone:ro
networks: {}
