version: "3.8"
services:
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake
    restart: on-failure
    env_file:
      - ../common.env.public
    ports:
      - 5800:5800
    devices:
      - /dev/dri:/dev/dri # for intel hardware decode
    volumes:
      - /containers/handbrake/config:/config:rw
      - /containers/handbrake/storage:/storage:ro
      - ${HANDBRAKE_WATCH}:/watch:rw
      - ${HANDBRAKE_WATCH}:/output:rw
      - ${DATA_DIR}:/data
      - ${EXTRA_DIR}:/extra
      - ${BULK_DIR}:/bulk
networks: {}

