version: '3.3'
services:
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake
    restart: on-failure
    ports:
      - 5800:5800
    devices:
      - /dev/dri:/dev/dri # for intel hardware decode
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /containers/handbrake/config:/config:rw
      - /containers/handbrake/storage:/storage:ro
      - ${WATCH_DIR}:/watch:rw
      - ${OUTPUT_DIR}:/output:rw
networks: {}

# .env must define WATCH_DIR & OUTPUT_DIR
