version: "3.3"
services:
  handbrake:
    container_name: handbrake
    restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - /containers/handbrake/config:/config:rw
      - /containers/handbrake/storage:/storage:ro
      - /containers/handbrake/watch:/watch:rw
      - /containers/handbrake/output:/output:rw
    image: jlesage/handbrake
networks: {}
