version: '3.8'
services:
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake
    restart: on-failure
    ports:
      - 5800:5800
    devices:
      - /dev/dri:/dev/dri # for intel hardware decode
    volumes:
      - /containers/handbrake/config:/config:rw
      - /containers/handbrake/storage:/storage:ro
    extends:
      file: ../common.yaml
      service: media-access
networks: {}
