version: "3.9"
services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra
      - ${CONFIG_DIR}/audiobookshelf/config:/config
      - ${BULK_DIR}:/bulk
    restart: unless-stopped
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    ports:
      - 5000:5000
    volumes:
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra
      - ${CONFIG_DIR}/kavita/config:/kavita/config
      - ${BULK_DIR}:/bulk
    restart: unless-stopped
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - 4533:4533
    volumes:
      - ${CONFIG_DIR}/navidrome/data:/data
      - ${DATA_DIR}/music:/music:ro
      - ${DATA_DIR_EXTRA}:/extra
      - ${BULK_DIR}:/bulk
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    volumes:
      - ${CONFIG_DIR}/jellyfin-config:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra
      - ${BULK_DIR}:/bulk
    ports:
      - 8096:8096
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    networks:
      - servarr_bridge
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - 5057:5055
    volumes:
      - ${CONFIG_DIR}/jellyseerr-config/:/app/config
    restart: unless-stopped
    networks:
      - servarr_bridge
networks:
  servarr_bridge:
    external: true
