version: "3.8"
services:
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: always
    ports:
      - 13378:80
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/audiobookshelf/config:/config
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: always
    ports:
      - 5000:5000
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/kavita/config:/kavita/config
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: always
    ports:
      - 4533:4533
    extends:
      file: ../common.yaml
      service: media-access
    environment:
      - ND_MUSICFOLDER=/data/music
      - ND_DATAFOLDER=/navidrome/data
    volumes:
      - /containers/navidrome/data:/navidrome/data
networks:
  servarr_bridge:
    external: true
