version: "3.9"
services:
  audiobookshelf:
    restart: unless-stopped
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /containers/audiobookshelf/config:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra # optional
      - ${BULK_DIR}:/bulk # optional
      - /etc/timezone:/etc/timezone:ro
  kavita:
    restart: unless-stopped
    container_name: kavita
    image: jvmilazz0/kavita:latest
    ports:
      - 5000:5000
    volumes:
      - /containers/kavita/config:/kavita/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra # optional
      - ${BULK_DIR}:/bulk # optional
      - /etc/timezone:/etc/timezone:ro
  navidrome:
    restart: unless-stopped
    container_name: navidrome
    image: deluan/navidrome:latest
    ports:
      - 4533:4533
    volumes:
      - /containers/navidrome/data:/data
      - ${DATA_DIR}/music:/music:ro
      - ${DATA_DIR_EXTRA}:/extra # optional
      - ${BULK_DIR}:/bulk # optional
      - /etc/timezone:/etc/timezone:ro
  jellyfin:
    restart: unless-stopped
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    ports:
      - 8096:8096
    volumes:
      - /containers/jellyfin:/config
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra # optional
      - ${BULK_DIR}:/bulk # optional
      - /etc/timezone:/etc/timezone:ro
    devices:
      - /dev/dri:/dev/dri # for intel hardware decode
    environment:
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel # for intel hardware decode
    networks:
      - servarr_bridge
  jellyseerr:
    restart: unless-stopped
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - 5057:5055
    volumes:
      - /containers/jellyseerr/:/app/config
      - /etc/timezone:/etc/timezone:ro
    networks:
      - servarr_bridge
networks:
  servarr_bridge:
    external: true

# .env must define DATA_DIR, other DIR's can be deleted
