version: "3.8"
services:
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: on-failure
    ports:
      - 13378:80
    env_file:
      - ../common.env.public
    volumes:
      - /containers/audiobookshelf/config:/config
      - ${DATA_DIR}:/data
      - ${EXTRA_DIR}:/extra # optional
      - ${BULK_DIR}:/bulk # optional
      - /etc/timezone:/etc/timezone:ro
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: on-failure
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri # for intel hardware decode
    environment:
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel # for intel hardware decode
    env_file:
      - ../common.env.public
    volumes:
      - /containers/jellyfin:/config
      - ${DATA_DIR}:/data
      - ${EXTRA_DIR}:/extra # optional
      - ${BULK_DIR}:/bulk # optional
      - /etc/timezone:/etc/timezone:ro
    networks:
      - servarr_bridge
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: on-failure
    ports:
      - 5057:5055
    volumes:
      - /containers/jellyseerr/:/app/config
      - /etc/timezone:/etc/timezone:ro
    networks:
      - servarr_bridge
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: on-failure
    ports:
      - 5000:5000
    env_file:
      - ../common.env.public
    volumes:
      - /containers/kavita/config:/kavita/config
      - ${DATA_DIR}:/data
      - ${EXTRA_DIR}:/extra # optional
      - ${BULK_DIR}:/bulk # optional
      - /etc/timezone:/etc/timezone:ro
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: on-failure
    ports:
      - 4533:4533
    env_file:
      - ../common.env.public
    volumes:
      - /containers/navidrome/data:/data
      - ${DATA_DIR}/music:/music:ro
      - ${EXTRA_DIR}:/extra # optional
      - ${BULK_DIR}:/bulk # optional
      - /etc/timezone:/etc/timezone:ro
networks:
  servarr_bridge:
    external: true
