version: "3.8"
services:
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: on-failure
    ports:
      - 13378:80
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/audiobookshelf/config:/config
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: on-failure
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri # for intel hardware decode
    environment:
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel # for intel hardware decode
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/jellyfin:/config
    networks:
      - servarr_bridge
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: on-failure
    ports:
      - 5057:5055
    volumes:
      - /containers/jellyseerr/:/app/config
      - /etc/timezone:/etc/timezone:ro
    networks:
      - servarr_bridge
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: on-failure
    ports:
      - 5000:5000
    extends:
      file: ../common.yaml
      service: media-access
    volumes:
      - /containers/kavita/config:/kavita/config
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: on-failure
    ports:
      - 4533:4533
    extends:
      file: ../common.yaml
      service: media-access
    environment:
      - ND_MUSICFOLDER=/data/music
      - ND_DATAFOLDER=/navidrome/data
    volumes:
      - /containers/navidrome/data:/navidrome/data
networks:
  servarr_bridge:
    external: true
