services:
  midarr:
    container_name: midarr
    image: ghcr.io/midarrlabs/midarr-server:latest
    ports:
      - 4000:4000
    volumes:
      - ${DATA_DIR}:/data
      - ${DATA_DIR_EXTRA}:/extra
      - ${BULK_DIR}:/bulk
    environment:
      - APP_URL=http://midarr:4000
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOSTNAME=midarr-psql
      - SETUP_ADMIN_EMAIL=admin@email.com
      - SETUP_ADMIN_NAME=admin
      - SETUP_ADMIN_PASSWORD=somepassword # minimum length 12
      - RADARR_BASE_URL=radarr:7878
      - RADARR_API_KEY=${RADARR_API_KEY}
      - SONARR_BASE_URL=sonarr:8989
      - SONARR_API_KEY=${SONARR_API_KEY}
    depends_on:
      - midarr-psql
    networks:
      - servarr_bridge
  midarr-psql:
    container_name: midarr-psql
    image: postgres
    volumes:
      - /containers/midarr-psql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - servarr_bridge
networks:
  servarr_bridge:
    external: true
