version: "3.8"
services:
  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true
    volumes:
      - ${CONFIG_DIR}/qbittorrent-config/:/config
      - ${DATA_DIR}:/data/
      - ${DATA_DIR_EXTRA}:/extra/
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    restart: unless-stopped
    env_file:
      - general.env
    networks:
      - servarr_bridge
networks:
  servarr_bridge:
    external: true

# .env must define: VPN_ENABLED, VPN_USERNAME, & VPN_PASSWORD