version: "3.8"
services:
  vscode-server:
    image: linuxserver/code-server
    container_name: vscode-server
    restart: always
    ports:
      - 8445:8443
    extends:
      file: ../common.yaml
      service: media-access
    environment:
      - DEFAULT_WORKSPACE=/saffron
    volumes:
      - /home/$USER/saffron/:/saffron
      - /containers/vscode-server/config:/config
    networks:
      - saffron_default
networks:
  saffron_default:
    external: true
