version: "3.8"
services:
  vscode-server:
    image: linuxserver/code-server
    container_name: vscode-server
    ports:
      - 8445:8443
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - DEFAULT_WORKSPACE=/saffron #optional
    volumes:
      - /home/$USER/saffron/:/saffron
      - /containers/vscode-server/config:/config
      - /etc/timezone:/etc/timezone:ro
networks: {}
