version: "3.8"
services:
  vscode-server:
    image: linuxserver/code-server
    container_name: vscode-server
    restart: on-failure
    ports:
      - 8445:8443
    env_file:
      - ../common.env.public
    environment:
      - DEFAULT_WORKSPACE=/saffron
    volumes:
      - /home/$USER/saffron/:/saffron
      - /containers/vscode-server/config:/config
      - /etc/timezone:/etc/timezone:ro
networks: {}
