services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: on-failure
    ports:
      - 3001:3001
    extends:
      file: ../common.yaml
      service: base-settings
    volumes:
      - /containers/uptime-kuma/data:/app/data
networks: {}
