services:
  uptime-kuma:
    restart: unless-stopped
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - /containers/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    labels:
      - traefik.frontend.rule=Host:localhost;PathPrefixStrip:/uptime-kuma
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
