services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    extends:
      file: ../common.yaml
      service: base-settings
    ports:
      - 3001:3001
    volumes:
      - /containers/uptime-kuma/data:/app/data
    networks:
      - saffron_default
networks:
  saffron_default:
    external: true
