version: "3.8"
services:
  tdarr:
    image: haveagitgat/tdarr:latest
    container_name: tdarr
    restart: on-failure
    network_mode: bridge
    ports:
      - 8265:8265
      - 8266:8266
    devices:
      - /dev/dri:/dev/dri # for intel hardware decode
    env_file:
      - ../common.env.public
    environment:
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
    volumes:
      - /containers/tdarr/server:/app/server
      - /containers/tdarr/configs:/app/configs
      - /containers/tdarr/logs:/app/logs
      - /containers/tdarr/temp:/temp
      - /etc/timezone:/etc/timezone:ro
      - ${MEDIA_PATH}:/media
      - ${DATA_DIR}:/data
      - ${EXTRA_DIR}:/extra
      - ${BULK_DIR}:/bulk
networks: {}

# .env must define MEDIA_PATH & DATA_DIRs
