version: "3"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedByDefault=true
      - --providers.docker.defaultRule=Host(`swervy.local`) && PathPrefix(`/{{
        normalize .Name }}`)
    # - --providers.docker.useBindPortIP=true
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks: {}
