version: '3'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 85:80
      # - 443:443
      - 8085:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - '--api.insecure=true'
      - '--providers.docker'
      - '--providers.docker.exposedByDefault=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
networks: {}