version: "3.8"
services:
  ustreamer:
    image: pikvm/ustreamer:v6.62
    pull_policy: missing
    container_name: ustreamer
    restart: always
    devices:
      - /dev/video0:/dev/video0
    ports:
      - 8083:8080
    command: ustreamer --device /dev/video0 -b 32 -w 32 -r 1280x720 -q 60
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - saffron_default
networks:
  saffron_default:
    external: true
