services:
  ustreamer:
    image: pikvm/ustreamer:latest
    container_name: ustreamer
    restart: always
    devices:
      - /dev/video0:/dev/video0
    ports:
      - 8083:8080
    command: ustreamer --device /dev/video0 -b 32 -w 32 -r 1280x720 -q 60
    networks:
      - saffron_default
networks:
  saffron_default:
    external: true
