version: '3.8'
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: always
    network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - /containers/heimdall:/config
    extends:
      file: ../common.yaml
      service: base-settings
networks: {}
