version: "3.8"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /containers/heimdall:/config
    extends:
      file: ../common.yaml
      service: base-settings
    networks:
      - saffron_default
networks:
  saffron_default:
    external: true
