version: "3.8"
services:
  duplicati:
    image: linuxserver/duplicati:latest
    container_name: duplicati
    restart: always
    extends:
      file: ../common.yaml
      service: media-access
    entrypoint:
      - /init
    ports:
      - 8200:8200/tcp
    environment:
      - PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/config
    volumes:
      - /containers/duplicati/config:/config
    ipc: private
    networks:
      - saffron_default
networks:
  saffron_default:
    external: true
