version: "3.8"
services:
  duplicati:
    image: linuxserver/duplicati:latest
    container_name: duplicati
    restart: on-failure
    entrypoint:
      - /init
    env_file:
      - ../common.env.public
    ports:
      - 8200:8200/tcp
    environment:
      - PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/config
    volumes:
      - /nas:/nas # optional
      - /containers/duplicati/config:/config
    ipc: private
networks: {}