version: '3.8'
services:
  duplicati:
    image: linuxserver/duplicati:latest
    container_name: duplicati
    restart: on-failure
    entrypoint:
      - /init
    extends:
      file: ../common.yaml
      service: base-settings
    ports:
      - 8200:8200/tcp
    environment:
      - PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/config
    volumes:
      - /containers/duplicati/config:/config
      - /nas:/nas # optional
    ipc: private
networks: {}
