version: '3.8'

services:
  dockge:
    container_name: dockge
    image: louislam/dockge:latest
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKGE_DATA_DIR}:/app/data
      - ${DOCKGE_STACKS_DIR}:${DOCKGE_STACKS_DIR}
    env_file:
      - .env
    restart: always
